language: node_js
node_js:
  - "node"
jobs:
  include:
   - stage: build
     script: npm run build
   - stage: test
     script: npm run testtest
    - stage: deploy
      deploy:
        provider: azure_web_apps