language: node_js
node_js:
  - "node"
jobs:
  include:
    - stage: build
      script: npm build
    - stage: test
      script: npm test
    - stage: deploy
      deploy:
        provider: azure_web_apps